apiVersion: v1
kind: Pod
metadata:
  name: multi-container-pod
  namespace: my-namespace
spec:
  containers:
    - name: hello-world-container
      image: nginx:latest
      ports:
        - containerPort: 80
    - name: hello-world-container-2
      image: nginx:latest
      command: ["sh", "-c"]
      args:
        - nginx -g "daemon off;" -c /etc/nginx/nginx.conf

