apiVersion: v1
kind: Pod
metadata:
  name: multi-container-pod
  namespace: my-namespace
spec:
  containers:
    - name: nginx
      image: nginhn:latest
      ports:
        - containerPort: 80

    - name: sidecar
      image: busybox
      command: ["sh","-c","while true; do echo sidecar running; sleep 5; done"]
