apiVersion: v1
kind: Namespace
metadata:
  name: my-namespace  
  labels:
    environment: production
    team: devops
  annotations:
    owner: "https://example.com/owner"  
spec:
  containers:
    - name: hello-pod
      image: nginx
      ports:
        - containerPort: 80
    - name: almalinux
      image: almalinux:8
      command: ["/bin/bash", "-c", "sleep 300"]